project:
  type: website
  output-dir: docs

website:
  title: "Particles"
  site-url: "https://royfrancis.github.io/quarto-particles/"
  description: "A quarto extension to add Particles.JS component"
  navbar:
    left:
      - text: "Home"
        href: "index.html"
        aria-label: "Home"
      - text: "Presentation"
        href: "revealjs.html"
        aria-label: "RevealJS Presentation"
      - text: "Versions"
        href: "changelog.html"
        aria-label: "Change log"
    right:
      - icon: github
        aria-label: "GitHub"
        href: https://github.com/royfrancis/quarto-particles
  page-footer:
    border: false
    left: "{{< meta current_year >}} Roy Francis • [MIT License](https://choosealicense.com/licenses/mit/)"
    right: "Published with [Quarto](https://quarto.org/) v{{< meta quarto_version >}}"

format:
  html:
   theme: pulse

filters:
  - custom.lua

